### ISSUE TITLE
Next release

### ISSUE THREAD

**Issue by gregmolnar** [textacular/textacular#81]
Here is the list of tasks I think we could do before the next release:
- [x] #60 Remove the deprecated methods. This only applies if we do a major release
- [ ] #73 This would be a neat new feature but I am not sure whether it can be done or not. We need to do some research
- [ ] #39 Another nice new possible addition

I think these are the open issues we should close and we could do a major release, and maybe drop Rails 3 support. What do you think @benhamill @ecin ?
We also fixed a few bugs on master so we could also do a patch release from current master.
//cc @simi

**Comment by benhamill** [comment]
The check boxes didn't render. Sad times.

ANYWAY... I vote for this timeline:

1. A patch release to get the 4 unreleased fixes into the current major line.
1. Remove the deprecated stuff and do a new major release.
1. Talk about adding other new features as minor releases thereafter.

I think we could cut 3.2.2 today (or whenever someone has time), if we wanted.

**Comment by simi** [comment]
try this
```
* [ ] check 1
```

**Comment by gregmolnar** [comment]
@simi Thanks :)
@benhamill I think it would be nice to add some new features with the major release and if we want to add those features we may need to break backward compatibility so major release would be a better choice to add them. 
I will have some time next week and I will take a look how could we implement those features and @simi also kindly offered his help.
I will leave the patch release for you :)

**Comment by gregmolnar** [comment]
I release a patch version from master and created a `3-2-stable` branch to make it easy to backport bugfixes.
I bumped the master version to `4.0.0.alpha` and will merge #82 into that. Then next week I will look into how to get those new features done.

**Comment by benhamill** [comment]
You're the best. :heart:

**Comment by simi** [comment]
@gregmolnar I think it is reasonable to release only with #60 in since #73 and #39 are inactive now.

**Comment by wyaeld** [comment]
@gregmolnar is there a list of changes needed for rails5, if any?

**Comment by gregmolnar** [comment]
@wyaeld master is working with rails 5, no changes needed.

**Comment by simi** [comment]
I think release was already done. Time to close this?
